"""Script 06: Generate subdivision data QA report.

Reads all intermediate files from the pipeline and produces a markdown
QA report summarizing data quality, coverage, and gaps.

Outputs:
  docs/data-sources/subdivision-matching-report.md

Usage:
  python -m scripts.data.subdivisions.06_generate_qa_report
"""

from __future__ import annotations

import json
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from scripts.data_sources import PROJECT_ROOT

INTERIM_DIR = PROJECT_ROOT / "data/interim/subdivisions"
DOCS_DIR = PROJECT_ROOT / "docs/data-sources"

RECORDS_PATH = INTERIM_DIR / "subdivision_records.json"
LINKS_PATH = INTERIM_DIR / "parcel_subdivision_links.json"
UNMATCHED_PATH = INTERIM_DIR / "unmatched_parcels.json"
NAME_INDEX_PATH = INTERIM_DIR / "subdivision_name_index.json"
CANDIDATES_PATH = INTERIM_DIR / "subdivision_candidates.json"
GIS_REPORT_PATH = INTERIM_DIR / "cook_gis_parcel_field_report.json"
DOWNLOAD_REPORT_PATH = INTERIM_DIR / "download_report.json"
OUTPUT_PATH = DOCS_DIR / "subdivision-matching-report.md"


def main() -> None:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)

    print("=== Generating Subdivision QA Report ===\n")

    records = load_json(RECORDS_PATH) or []
    links = load_json(LINKS_PATH) or []
    unmatched = load_json(UNMATCHED_PATH) or []
    name_index = load_json(NAME_INDEX_PATH) or {}
    gis_report = load_json(GIS_REPORT_PATH) or {}
    download_report = load_json(DOWNLOAD_REPORT_PATH) or {}

    report_lines = build_report(records, links, unmatched, name_index, gis_report, download_report)
    OUTPUT_PATH.write_text("\n".join(report_lines), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(PROJECT_ROOT)}")

    # Summary to console
    print(f"\nSummary:")
    print(f"  Unique subdivisions found: {len(records)}")
    print(f"  Parcel-subdivision links: {len(links)}")
    print(f"  Unmatched parcels: {len(unmatched)}")
    total = len(links) + len(unmatched)
    if total > 0:
        match_pct = round(len(links) / total * 100, 1)
        print(f"  Match rate: {match_pct}%")


def build_report(
    records: list[dict[str, Any]],
    links: list[dict[str, Any]],
    unmatched: list[dict[str, Any]],
    name_index: dict[str, Any],
    gis_report: dict[str, Any],
    download_report: dict[str, Any],
) -> list[str]:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    total_processed = len(links) + len(unmatched)
    match_pct = round(len(links) / max(total_processed, 1) * 100, 1)

    confidence_counts = Counter(link.get("confidence_level", "unknown") for link in links)
    by_confidence = {level: confidence_counts.get(level, 0) for level in ("high", "medium", "low", "unknown")}

    # Top subdivisions by parcel count
    by_count = sorted(records, key=lambda r: -(r.get("parcel_count") or 0))
    top_subdivisions = by_count[:20]

    # Missing data checks
    missing_recorded_year = sum(1 for r in records if not r.get("recorded_year"))
    missing_owner = sum(1 for r in records if not r.get("original_owner"))
    missing_source = sum(1 for r in records if not r.get("source_name"))

    # GIS field status
    gis_sub_fields = gis_report.get("subdivision_candidate_fields", [])
    gis_status = "Found" if gis_sub_fields else "Not found"

    lines = [
        "# Subdivision Matching Report",
        "",
        f"Generated: {now}",
        "",
        "This report summarizes the current state of subdivision data for Park Ridge, Illinois.",
        "It is automatically generated by `scripts/data/subdivisions/06_generate_qa_report.py`.",
        "",
        "---",
        "",
        "## Summary",
        "",
        f"| Metric | Value |",
        f"|--------|-------|",
        f"| Total subdivisions identified | {len(records)} |",
        f"| Total parcel-subdivision links | {len(links)} |",
        f"| Unmatched parcels | {len(unmatched)} |",
        f"| Overall match rate | {match_pct}% |",
        f"| High-confidence links | {by_confidence['high']} |",
        f"| Medium-confidence links | {by_confidence['medium']} |",
        f"| Low-confidence links | {by_confidence['low']} |",
        f"| Unknown-confidence links | {by_confidence['unknown']} |",
        "",
        "---",
        "",
        "## Data Source Status",
        "",
        f"| Source | Status |",
        f"|--------|--------|",
        f"| Cook County GIS parcel subdivision field | {gis_status} |",
        f"| GIS fields available | {', '.join(f['name'] for f in gis_sub_fields) if gis_sub_fields else 'None'} |",
        f"| GIS features downloaded | {download_report.get('features_downloaded', 'N/A')} |",
        f"| Features with subdivision value | {download_report.get('features_with_subdivision_value', 'N/A')} |",
        "",
        "---",
        "",
        "## Missing Data",
        "",
        f"| Gap | Count |",
        f"|-----|-------|",
        f"| Subdivisions missing recorded year | {missing_recorded_year} of {len(records)} |",
        f"| Subdivisions missing original owner | {missing_owner} of {len(records)} |",
        f"| Subdivisions missing source citation | {missing_source} of {len(records)} |",
        "",
        "---",
        "",
        "## Top 20 Subdivisions by Parcel Count",
        "",
        "| Rank | Subdivision Name | Parcels | Confidence | Source |",
        "|------|-----------------|---------|------------|--------|",
    ]

    for i, sub in enumerate(top_subdivisions, 1):
        lines.append(
            f"| {i} | {sub.get('name', 'Unknown')} | "
            f"{sub.get('parcel_count', 0)} | "
            f"{sub.get('confidence_level', 'unknown')} | "
            f"{sub.get('source_name', 'Unknown')[:40] if sub.get('source_name') else 'Unknown'} |"
        )

    lines += [
        "",
        "---",
        "",
        "## Confidence Distribution",
        "",
        "| Confidence | Links | Percent |",
        "|------------|-------|---------|",
    ]
    for level in ("high", "medium", "low", "unknown"):
        count = by_confidence[level]
        pct = round(count / max(len(links), 1) * 100, 1)
        lines.append(f"| {level.capitalize()} | {count} | {pct}% |")

    lines += [
        "",
        "---",
        "",
        "## Methodology",
        "",
        "Subdivision matching was performed using the following priority order:",
        "",
        "1. Cook County GIS parcel attribute field (`subdivisio` or equivalent)",
        "2. Park Ridge land family CSV (manually researched clues)",
        "3. Fuzzy name matching against known subdivision names",
        "",
        "For full methodology, see `docs/methodology/subdivision-history-methodology.md`.",
        "",
        "---",
        "",
        "## Known Gaps",
        "",
        "- Recorded subdivision dates are NOT available in the Cook County GIS parcel layer.",
        "  Recording dates require research in the Cook County Recorder plat database.",
        "- Original owners and developers are NOT available programmatically.",
        "  These require research in recorded plat documents or historical directories.",
        "- Subdivision boundaries have NOT been georeferenced.",
        "  Boundaries would require digitizing from recorded plat maps.",
        "- Pre-1985 plat records may be difficult to access online.",
        "  In-person research at the Cook County Recorder's office may be needed.",
        "",
        "See `docs/data-sources/manual-research-queue.md` for items requiring manual research.",
        "",
        "---",
        "",
        "*This report is for research purposes. Data is from public sources and may be incomplete.*",
    ]

    return lines


def load_json(path: Path) -> Any:
    if not path.exists():
        return None
    with path.open(encoding="utf-8") as f:
        return json.load(f)


if __name__ == "__main__":
    main()
