import type { HistoricalLayer } from "./historicalLayerTypes";

const cookPortal = "https://datacatalog.cookcountyil.gov/";
const ilhapCook = "https://clearinghouse.isgs.illinois.edu/webdocs/ilhap/county/j_cook.html";
const parkRidgeMaps = "https://storymaps.arcgis.com/collections/94130fe6114d4606af97b11fd0875e25";

export const defaultHistoricalLayers: HistoricalLayer[] = [
  {
    id: "cook_parcels_2000",
    name: "Cook County Parcels 2000",
    description: "Official Cook County 2000 parcel snapshot spatially filtered to Park Ridge.",
    type: "vector",
    status: "ready",
    year: 2000,
    sourceName: "Cook County 2000Parcels",
    sourceUrl: "https://datacatalog.cookcountyil.gov/Property-Taxation/2000Parcels/bbcr-ryng",
    attribution: "Cook County GIS / Cook County Open Data.",
    historicalQuestion: "What did parcel boundaries look like in this tax year?",
    layerGroup: "parcel_boundaries",
    dataPath: "/data/historical/cook_parcels_2000.geojson",
    opacityDefault: 0.85,
    enabledDefault: false,
    notes: "Downloaded from the Cook County 2000 parcel snapshot and filtered by centroid within the current Park Ridge municipal boundary. Year built is not subdivision date."
  },
  {
    id: "cook_parcels_2004",
    name: "Cook County Parcels 2004",
    description: "Historical parcel boundary layer registration placeholder.",
    type: "vector",
    status: "needs_download",
    year: 2004,
    sourceName: "Cook County Historical GIS Data Portal",
    sourceUrl: cookPortal,
    attribution: "Cook County GIS when downloaded.",
    historicalQuestion: "Which parcel boundaries existed in 2004?",
    layerGroup: "parcel_boundaries",
    opacityDefault: 0.85,
    notes: "Register downloaded and normalized data at public/data/historical/parcels_2004.geojson."
  },
  {
    id: "cook_parcels_2009",
    name: "Cook County Parcels 2009",
    description: "Historical parcel boundary layer registration placeholder.",
    type: "vector",
    status: "needs_download",
    year: 2009,
    sourceName: "Cook County Historical GIS Data Portal",
    sourceUrl: cookPortal,
    attribution: "Cook County GIS when downloaded.",
    historicalQuestion: "Which parcel boundaries existed in 2009?",
    layerGroup: "parcel_boundaries",
    opacityDefault: 0.85
  },
  {
    id: "cook_parcels_2019",
    name: "Cook County Parcels 2019",
    description: "Historical parcel boundary layer registration placeholder.",
    type: "vector",
    status: "needs_download",
    year: 2019,
    sourceName: "Cook County Historical GIS Data Portal",
    sourceUrl: cookPortal,
    attribution: "Cook County GIS when downloaded.",
    historicalQuestion: "Which parcel boundaries existed in 2019?",
    layerGroup: "parcel_boundaries",
    opacityDefault: 0.85
  },
  {
    id: "cook_parcels_2020",
    name: "Cook County Parcels 2020",
    description: "Historical parcel boundary layer registration placeholder.",
    type: "vector",
    status: "needs_download",
    year: 2020,
    sourceName: "Cook County Historical GIS Data Portal",
    sourceUrl: cookPortal,
    attribution: "Cook County GIS when downloaded.",
    historicalQuestion: "Which parcel boundaries existed in 2020?",
    layerGroup: "parcel_boundaries",
    opacityDefault: 0.85
  },
  {
    id: "cook_parcels_2021",
    name: "Cook County Parcels 2021",
    description: "Official Cook County 2021 parcel snapshot filtered to Park Ridge municipal parcels.",
    type: "vector",
    status: "ready",
    year: 2021,
    sourceName: "Cook County ccgisdata - Parcel 2021",
    sourceUrl: "https://datacatalog.cookcountyil.gov/Boundaries-Districts/ccgisdata-Parcel-2021/77tz-riq7",
    attribution: "Cook County GIS / Cook County Open Data.",
    historicalQuestion: "What changed between parcel boundary years?",
    layerGroup: "parcel_boundaries",
    dataPath: "/data/historical/cook_parcels_2021.geojson",
    opacityDefault: 0.85,
    enabledDefault: false,
    notes: "Downloaded from the Cook County 2021 parcel snapshot and filtered to municipality = Park Ridge."
  },
  {
    id: "cook_recorded_subdivision_plats",
    name: "Recorded Subdivision Plat Lots",
    description: "Future vector layer for lots created by recorded subdivision plats.",
    type: "vector",
    status: "manual_research_required",
    sourceName: "Cook County recorded plats / Recorder research",
    attribution: "Cook County Clerk / Recorder sources when obtained.",
    historicalQuestion: "What legal plat evidence exists for formal land subdivision?",
    layerGroup: "subdivision_plats",
    notes: "Plat date is the evidence needed for subdivision history; assessor year-built is not sufficient."
  },
  {
    id: "ilhap_cook_1938_1939",
    name: "ILHAP Cook County 1938/1939",
    description: "Historical aerial imagery showing prewar land cover and early subdivision patterns.",
    type: "image_overlay",
    status: "needs_georeferencing",
    yearRange: [1938, 1939],
    sourceName: "Illinois Historical Aerial Photography",
    sourceUrl: ilhapCook,
    attribution: "Illinois State Geological Survey / ILHAP.",
    historicalQuestion: "What physical development was visible before postwar suburban buildout?",
    layerGroup: "aerial_imagery",
    requiresGeoreferencing: true,
    opacityDefault: 0.65,
    notes: "Download frames covering Park Ridge, georeference, then tile before enabling."
  },
  ...[1970, 1975, 1980, 1985, 1990, 1995].map((year) => ({
    id: `cmap_aerial_${year}`,
    name: `CMAP Aerial ${year}`,
    description: "Placeholder for CMAP historical aerial imagery.",
    type: "raster_tile" as const,
    status: "needs_download" as const,
    year,
    sourceName: "CMAP Imagery Explorer",
    sourceUrl: "https://www.cmap.illinois.gov/data/imagery",
    attribution: "CMAP imagery when downloaded or linked.",
    historicalQuestion: "How did visible land cover and development change between 1970 and 1995?",
    layerGroup: "aerial_imagery" as const,
    requiresGeoreferencing: true,
    opacityDefault: 0.65,
    notes: "Confirm tile-ready access or prepare georeferenced tiles before enabling."
  })),
  {
    id: "cook_county_imagery_1998_plus",
    name: "Cook County Modern Imagery 1998+",
    description: "Placeholder for modern Cook County aerial imagery services where publicly usable.",
    type: "raster_tile",
    status: "needs_download",
    yearRange: [1998, 2026],
    sourceName: "Cook County GIS",
    sourceUrl: "https://gis.cookcountyil.gov/",
    attribution: "Cook County GIS imagery when configured.",
    historicalQuestion: "What recent physical changes are visible after 1998?",
    layerGroup: "aerial_imagery",
    opacityDefault: 0.65
  },
  {
    id: "park_ridge_historic_landmarks",
    name: "Park Ridge Historic Landmarks",
    description: "Local preservation context layer from Park Ridge public GIS when available.",
    type: "vector",
    status: "manual_research_required",
    sourceName: "Park Ridge Map Gallery",
    sourceUrl: parkRidgeMaps,
    attribution: "City of Park Ridge GIS when configured.",
    historicalQuestion: "Which properties have local historic landmark context?",
    layerGroup: "local_history"
  },
  {
    id: "park_ridge_100_year_old_homes",
    name: "Park Ridge 100 Year-Old Homes",
    description: "Local context layer for 100-year-old homes where public GIS access is available.",
    type: "vector",
    status: "manual_research_required",
    sourceName: "Park Ridge Map Gallery",
    sourceUrl: parkRidgeMaps,
    attribution: "City of Park Ridge GIS when configured.",
    historicalQuestion: "Which structures are recognized locally as 100-year-old homes?",
    layerGroup: "local_history",
    notes: "This is preservation/context evidence, not subdivision evidence."
  },
  {
    id: "cook_county_plss_sections",
    name: "PLSS Sections",
    description: "Public Land Survey System context for township/section geography.",
    type: "vector",
    status: "needs_download",
    sourceName: "Cook County GIS / PLSS reference data",
    sourceUrl: "https://gis.cookcountyil.gov/",
    attribution: "Cook County GIS or authoritative PLSS source when configured.",
    historicalQuestion: "What survey framework underlies parcel geography?",
    layerGroup: "survey_grid",
    opacityDefault: 0.35
  },
  {
    id: "sample_parcel_changes_2000_2021",
    name: "Sample Parcel Changes 2000-2021",
    description: "Synthetic parcel change candidates showing splits, merges, new PINs, retired PINs, and area changes.",
    type: "vector",
    status: "ready",
    yearRange: [2000, 2021],
    sourceName: "Synthetic sample",
    attribution: "Synthetic sample data.",
    historicalQuestion: "Which boundary changes are candidates for further verification?",
    layerGroup: "parcel_boundaries",
    dataPath: "/data/historical/sample_parcel_changes_2000_2021.geojson",
    opacityDefault: 0.55,
    syntheticSample: true,
    notes: "Change types are candidates and need verification against official records."
  },
  {
    id: "sanborn_park_ridge_placeholder",
    name: "Sanborn Map Sheets",
    description: "Future georeferenced map sheets for historic block-level building and land-use evidence.",
    type: "georeferenced_map_sheet",
    status: "future",
    sourceName: "Sanborn Fire Insurance Maps",
    attribution: "Sanborn source and license required when obtained.",
    historicalQuestion: "What building footprints, materials, uses, and addresses are documented on historic sheets?",
    layerGroup: "sanborn",
    requiresGeoreferencing: true,
    notes: "Access and licensing vary; do not assume open API access."
  }
];
