from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd
from dotenv import load_dotenv

from scripts.data_sources import DATA_SOURCES, PROJECT_ROOT
from scripts.pipeline_utils import (
    BUILDING_SQFT_COLUMN_CANDIDATES,
    PIN_COLUMN_CANDIDATES,
    YEAR_BUILT_COLUMN_CANDIDATES,
    find_likely_column,
)


def read_source_preview(path: Path) -> tuple[pd.DataFrame, bool]:
    suffix = path.suffix.lower()
    if suffix in {".geojson", ".json", ".gpkg", ".shp"}:
        import geopandas as gpd

        frame = gpd.read_file(path)
        return pd.DataFrame(frame.drop(columns="geometry", errors="ignore")), "geometry" in frame
    return pd.read_csv(path, nrows=5000, dtype="string"), False


def inspect_file(path: Path) -> dict[str, Any] | None:
    if not path.exists():
        return None

    frame, has_geometry = read_source_preview(path)
    columns = list(frame.columns)
    return {
        "path": path,
        "row_count_preview": len(frame),
        "columns": columns,
        "likely_pin_column": find_likely_column(columns, PIN_COLUMN_CANDIDATES),
        "likely_year_built_column": find_likely_column(columns, YEAR_BUILT_COLUMN_CANDIDATES),
        "likely_building_sqft_column": find_likely_column(columns, BUILDING_SQFT_COLUMN_CANDIDATES),
        "has_geometry": has_geometry,
        "sample_rows": frame.head(3).fillna("").to_dict(orient="records"),
    }


def write_dictionary(results: list[tuple[str, dict[str, Any] | None]]) -> None:
    output = PROJECT_ROOT / "docs/data_dictionary.md"
    lines = [
        "# Data Dictionary and Schema Inspection",
        "",
        "This file is generated by `python scripts/inspect_sources.py` and should be refreshed when source files change.",
        "",
    ]

    for source_name, result in results:
        lines.extend([f"## {source_name}", ""])
        if result is None:
            lines.extend(["Source file not found. Add a local file or configure a source URL in `.env`.", ""])
            continue

        relative_path = result["path"].relative_to(PROJECT_ROOT)
        lines.extend(
            [
                f"- Path: `{relative_path}`",
                f"- Preview row count: `{result['row_count_preview']}`",
                f"- Geometry detected: `{result['has_geometry']}`",
                f"- Likely PIN column: `{result['likely_pin_column'] or 'not detected'}`",
                f"- Likely year-built column: `{result['likely_year_built_column'] or 'not detected'}`",
                f"- Likely building sqft column: `{result['likely_building_sqft_column'] or 'not detected'}`",
                "",
                "### Columns",
                "",
            ]
        )
        lines.extend(f"- `{column}`" for column in result["columns"])
        lines.extend(["", "### Sample Rows", ""])
        for row in result["sample_rows"]:
            lines.append(f"- `{row}`")
        lines.append("")

    output.write_text("\n".join(lines), encoding="utf-8")
    print(f"\nWrote {output.relative_to(PROJECT_ROOT)}")


def main() -> None:
    load_dotenv(PROJECT_ROOT / ".env")
    results: list[tuple[str, dict[str, Any] | None]] = []

    for source in DATA_SOURCES:
        print(f"\n{source.name}")
        print(f"  Expected path: {source.local_path.relative_to(PROJECT_ROOT)}")
        result = inspect_file(source.local_path)
        results.append((source.name, result))
        if result is None:
            print("  File missing.")
            continue
        print(f"  Rows previewed: {result['row_count_preview']}")
        print(f"  Columns: {', '.join(result['columns'])}")
        print(f"  Likely PIN column: {result['likely_pin_column'] or 'not detected'}")
        print(f"  Likely year-built column: {result['likely_year_built_column'] or 'not detected'}")
        print(f"  Geometry detected: {result['has_geometry']}")

    write_dictionary(results)


if __name__ == "__main__":
    main()
