-- Research queue for tracking which properties to investigate at Cook County.
-- Entries are generated by finding spatial neighbors of already-deed-researched
-- properties that have no subdivision link yet.

CREATE TABLE deed_research_queue (
  id                        uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  pin                       text        NOT NULL,
  address                   text,
  suspected_subdivision_id  uuid        REFERENCES subdivisions(id) ON DELETE SET NULL,
  suspected_subdivision_name text,
  ai_reasoning              text        NOT NULL DEFAULT '',
  priority_score            numeric     NOT NULL DEFAULT 0,
  source_pins               text[],
  status                    text        NOT NULL DEFAULT 'pending'
                            CHECK (status IN ('pending', 'researched', 'not_found', 'skipped')),
  created_at                timestamptz NOT NULL DEFAULT now(),
  updated_at                timestamptz NOT NULL DEFAULT now(),
  UNIQUE (pin)
);

ALTER TABLE deed_research_queue ENABLE ROW LEVEL SECURITY;
-- Admin-only: no public or authenticated access
CREATE POLICY "admin_only" ON deed_research_queue USING (false);

-- Function: find candidate properties to add to the research queue.
-- Returns up to 50 unresearched Park Ridge parcels that are spatially adjacent
-- to properties already linked to a subdivision via deed legal description.
-- Excludes parcels already in the queue with terminal statuses.
CREATE OR REPLACE FUNCTION find_research_candidates()
RETURNS TABLE(
  candidate_pin              text,
  candidate_address          text,
  suspected_subdivision_id   uuid,
  suspected_subdivision_name text,
  source_pins                text[],
  neighbor_count             bigint,
  anchor_lots                text[],
  anchor_blocks              text[],
  anchor_addresses           text[]
)
LANGUAGE sql
SECURITY DEFINER
STABLE
AS $$
  SELECT
    candidates.pin_normalized,
    candidates.address,
    anchors.subdivision_id,
    anchors.subdivision_name,
    array_agg(DISTINCT anchors.anchor_pin)                                          AS source_pins,
    COUNT(DISTINCT anchors.anchor_pin)                                              AS neighbor_count,
    array_agg(DISTINCT anchors.lot_number)   FILTER (WHERE anchors.lot_number   IS NOT NULL) AS anchor_lots,
    array_agg(DISTINCT anchors.block_number) FILTER (WHERE anchors.block_number IS NOT NULL) AS anchor_blocks,
    array_agg(DISTINCT anchors.anchor_address)                                      AS anchor_addresses
  FROM parcels candidates
  JOIN (
    SELECT
      p.pin_normalized    AS anchor_pin,
      p.address           AS anchor_address,
      p.geometry          AS anchor_geometry,
      psl.subdivision_id,
      s.name              AS subdivision_name,
      psl.lot_number,
      psl.block_number
    FROM   parcels p
    JOIN   property_subdivision_links psl ON psl.pin = p.pin_normalized
    JOIN   subdivisions               s   ON s.id   = psl.subdivision_id
    WHERE  psl.match_method = 'deed_legal_description'
      AND  p.geometry IS NOT NULL
  ) anchors
    ON ST_DWithin(candidates.geometry, anchors.anchor_geometry, 0.0003)
  WHERE  candidates.municipality = 'CITY OF PARK RIDGE'
    AND  candidates.geometry IS NOT NULL
    AND  candidates.pin_normalized != anchors.anchor_pin
    AND  candidates.pin_normalized NOT IN (
           SELECT pin FROM property_subdivision_links
         )
    AND  candidates.pin_normalized NOT IN (
           SELECT pin FROM deed_research_queue
           WHERE  status IN ('researched', 'not_found', 'skipped')
         )
  GROUP BY candidates.pin_normalized, candidates.address,
           anchors.subdivision_id, anchors.subdivision_name
  ORDER BY neighbor_count DESC
  LIMIT 50
$$;
